set slut="%cd%"
md ".\Yummy"
set pavitra="D:\paradise\stuff\Essence\FS\all\Devi\ForImage"
set resultFolder=".\Yummy"
"C:\Users\HP\Miniconda3\scripts\activate.bat" && conda activate "faceswap" && python "D:\Developed\FaceSwapExperimental\vfs.py" %slut% %pavitra% %resultFolder% 5 && "D:\Developed\VFS\RandyVideo\framesCsv.bat"